slack:
  token: something
  error_channel: errors_channel_name
google:
  sheet_url: https://docs.google.com/spreadsheets/d/1_DcvojpHzpZixOts6BApy0neiqtwjJkhVdMBqJVucgM/edit#gid=1956562684
  credentials: credentials.json
scto:
  username: email
  password: password
  host: host/server_name

